### ISSUE TITLE
Application Error #200 when clicking Send button

### ISSUE THREAD

**Issue by sintaq83** [mantisbt-plugins/Forward#1]
Application Error #200 when clicking Send button. Refer attached image

<img width="910" alt="Capture" src="https://github.com/mantisbt-plugins/Forward/assets/79757612/c1441e3e-a904-4e8b-b008-84a17592feec">

**Comment by ghost** [comment]
I cannot replicate this. Can you add the following line into core/config_inc.php:
$g_show_detailed_errors = ON;
Now try again, you should get more info


From: sintaq83 ***@***.***>
Sent: Thursday, June 1, 2023 9:53 AM
To: mantisbt-plugins/Forward ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mantisbt-plugins/Forward] Application Error #200 when clicking Send button (Issue #1)


Application Error #200 when clicking Send button. Refer attached image
[Capture]<https://user-images.githubusercontent.com/79757612/242526179-c1441e3e-a904-4e8b-b008-84a17592feec.PNG>

**Comment by mokraemer** [comment]
I can confirm this one too.

Detailed error information
Full path: /core/gpc_api.php
Line number: 68
Stack trace
#	Filename	Line	Class	Type	Function	Args
0	/core/gpc_api.php	68	-	-	trigger_error	<string>'200', <integer>256
1	/core/gpc_api.php	128	-	-	gpc_get	<string>'forward_at'
2	/plugins/Forward/pages/issue_send.php	13	-	-	gpc_get_int	<string>'forward_at'
3	/plugin.php	74	-	-	include	<string>'/plugins/Forward/pages/issue_send.php'

**Comment by ghost** [comment]
Found the issue and fixed it also. Please use a fresh download from here

**Comment by dregad** [comment]
@CasN Maybe because the *forward_at* input is commented out ? you should consider calling gpc_get_int() with a default value.

https://github.com/mantisbt-plugins/Forward/blob/b5895dca8714231254b73cab184948159fd56c30/pages/issue_send_page.php#L64-L74

**Comment by ghost** [comment]
@dregad, not sure how but some development work ended up there, have already taken care of it😊
Thanks for the tip.

**Comment by dregad** [comment]
Funny we posted at literally the same time 🎯

**Comment by sintaq83** [comment]
@CasN  @dregad thanks guys
