### ISSUE TITLE
Add CC: and attachment fields and populate To: and Cc:

### ISSUE THREAD

**Issue by jporradre** [mantisbt-plugins/Forward#3]
I would like to know if is it possible to add two additional fields to the forward UI (Cc and attachment) and also populate the To: and Cc: fields with the respective addresses of the original mail that created the bug with Emailreporting plugin, or if the was another workaround to do that in the meantime.

Thanks in advance,

Juan Pablo.

**Comment by ghost** [comment]
In the address area, you can define multiple addresses separated with a comma. In the latest version (not released yet), I also provide an overview of current attachments. Is that what you mean or do you expect the attachments to be added to this mail also? In addition, custom fields can be added to the mail.

**Comment by ghost** [comment]
Version 2.21 has the option to send mail also to reporter

**Comment by jporradre** [comment]
Hi Cas! OK thanks to the changes you've made quickly.

Unfortunately that wasn't exactly what I was needing, because I was trying to send with the mail all the bug attachments (not displaying it's details) , and send the email to the original sender and CC: addresses (not the fallback reporter email address that EmailReporting plugin assigns / mantis user email address).

Can you do that?

Thanks a lot!

**Comment by ghost** [comment]
I would not know how to fetch the email address of the original sender, it may be partof the issue and it may be not. As for attachments, think it could be done but that is not in scope for my plugin since I see that as a security risk (sending out attachments to anyone outside the organization).
